"""Pydantic data models for all Nashr entities (users, projects, sources, articles, decks)."""

from packages.core.models.article import (
    Article,
    ArticleCreate,
    ArticleOutline,
    ArticleSection,
    CitationRef,
    OutlineSection,
    Paragraph,
)
from packages.core.models.billing import (
    CreditLedgerEntry,
    GenerationJob,
    Order,
)
from packages.core.models.deck import (
    BackgroundSpec,
    CategoryItem,
    ColorEntry,
    ColorPalette,
    DebateOption,
    DebateScenario,
    Deck,
    DesignDirection,
    FillBlankItem,
    InteractiveSpec,
    MatchingPair,
    NavigationSpec,
    QuizFeedback,
    QuizOption,
    Slide,
    TrueFalseItem,
    TypographySpec,
    VisualSpec,
    VisualTheme,
)
from packages.core.models.evidence import (
    AnswerScore,
    EvidenceMatrixEntry,
    ResearchAnswer,
    ResearchQuestion,
)
from packages.core.models.project import Project, ProjectCreate
from packages.core.models.source import (
    FileValidationResult,
    OCRResult,
    ParsedPage,
    ParsedSource,
    Source,
    SourceChunk,
    SourceClaim,
    SourceCreate,
    SourceMetadata,
    SourceMetadataExtracted,
)
from packages.core.models.user import User, UserCreate

__all__ = [
    "AnswerScore",
    "Article",
    "ArticleCreate",
    "ArticleOutline",
    "ArticleSection",
    "BackgroundSpec",
    "CategoryItem",
    "CitationRef",
    "ColorEntry",
    "ColorPalette",
    "CreditLedgerEntry",
    "DebateOption",
    "DebateScenario",
    "Deck",
    "DesignDirection",
    "EvidenceMatrixEntry",
    "FileValidationResult",
    "FillBlankItem",
    "GenerationJob",
    "InteractiveSpec",
    "MatchingPair",
    "NavigationSpec",
    "OCRResult",
    "Order",
    "OutlineSection",
    "Paragraph",
    "ParsedPage",
    "ParsedSource",
    "Project",
    "ProjectCreate",
    "QuizFeedback",
    "QuizOption",
    "ResearchAnswer",
    "ResearchQuestion",
    "Slide",
    "Source",
    "SourceChunk",
    "SourceClaim",
    "SourceCreate",
    "SourceMetadata",
    "SourceMetadataExtracted",
    "TrueFalseItem",
    "TypographySpec",
    "User",
    "UserCreate",
    "VisualSpec",
    "VisualTheme",
]
