"""Evidence-matrix and research-interview models.

The evidence matrix is the core artifact for articles: it links every claim,
source chunk, user-supplied answer, and article section into a single graph.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field

from packages.core.enums import CitationStatus, ResearchQuestionType


class EvidenceMatrixEntry(BaseModel):
    """One row of the evidence matrix linking a claim to its supporting context."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    id: UUID = Field(default_factory=uuid4)
    project_id: UUID
    claim_id: UUID
    source_chunk_id: UUID
    user_answer_id: UUID | None = None
    article_section_id: UUID | None = None
    citation_status: CitationStatus
    created_at: datetime


class ResearchQuestion(BaseModel):
    """A question generated by the research-interview engine for the user to answer."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    id: UUID = Field(default_factory=uuid4)
    project_id: UUID
    question_text: str = Field(min_length=1, max_length=2000)
    question_type: ResearchQuestionType
    related_source_ids: list[UUID] = Field(default_factory=list)
    created_at: datetime


class AnswerScore(BaseModel):
    """Three-axis rubric scoring of a single user answer.

    Each axis is integer 0..5. The aggregate is intentionally not stored — it
    is computed on demand so that scoring rules can evolve without migration.
    """

    model_config = ConfigDict(extra="forbid")

    specificity: int = Field(ge=0, le=5)
    source_grounding: int = Field(ge=0, le=5)
    usefulness: int = Field(ge=0, le=5)


class ResearchAnswer(BaseModel):
    """A user's answer to a single research question."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    id: UUID = Field(default_factory=uuid4)
    project_id: UUID
    question_id: UUID
    answer_text: str = Field(min_length=1, max_length=10_000)
    source_references_used: list[UUID] = Field(default_factory=list)
    score: AnswerScore
    credits_earned: int = Field(ge=0, le=10)
    created_at: datetime
