"""Per-domain keyword dictionaries used by :class:`DomainDetector`.

Stored separately so the detector module stays compact. Each set is the
*canonical* lower-cased form: the detector lowercases the article-derived
text blob before matching, so adding "GDP" here would never match "gdp"
in user content. Keep entries lower-case.

Entries deliberately mix English, Uzbek (Latin script), and Russian so
articles written in any of Nashr's three supported languages route to the
right provider. Multi-word entries (e.g. "machine learning") are matched
as substrings of the lower-cased blob.
"""

from __future__ import annotations

from packages.core.models.suggestion import AcademicDomain

DOMAIN_KEYWORDS: dict[AcademicDomain, frozenset[str]] = {
    AcademicDomain.MEDICAL: frozenset(
        {
            "patient",
            "clinical",
            "diagnosis",
            "treatment",
            "therapy",
            "disease",
            "symptom",
            "pharmaceutical",
            "dosage",
            "surgery",
            "hospital",
            "nurse",
            "epidemiology",
            "mortality",
            "morbidity",
            "pathology",
            "oncology",
            "randomized",
            "placebo",
            "cohort",
            "biomarker",
            "genome",
            "protein",
            "cell",
            "tissue",
            "organ",
            "infection",
            "vaccine",
            "antibiotic",
            "mental health",
            "depression",
            "anxiety",
            "chronic",
            "acute",
            "bemor",
            "kasallik",
            "davolash",
            "shifoxona",
            "tibbiyot",
            "dori",
            "diagnostika",
            "jarrohlik",
            "epidemiologiya",
            "пациент",
            "лечение",
            "диагноз",
            "болезнь",
            "терапия",
            "клинический",
            "больница",
            "хирургия",
            "фармакология",
        }
    ),
    AcademicDomain.ECONOMICS: frozenset(
        {
            "gdp",
            "inflation",
            "unemployment",
            "trade",
            "market",
            "fiscal",
            "monetary",
            "investment",
            "export",
            "import",
            "tariff",
            "subsidy",
            "poverty",
            "inequality",
            "economic growth",
            "recession",
            "currency",
            "interest rate",
            "stock",
            "bond",
            "banking",
            "microeconomic",
            "macroeconomic",
            "supply",
            "demand",
            "price",
            "cost",
            "revenue",
            "budget",
            "taxation",
            "public finance",
            "iqtisodiyot",
            "inflyatsiya",
            "ishsizlik",
            "savdo",
            "bozor",
            "investitsiya",
            "eksport",
            "soliq",
            "byudjet",
            "daromad",
            "экономика",
            "инфляция",
            "безработица",
            "торговля",
            "рынок",
            "инвестиции",
            "бюджет",
            "налог",
        }
    ),
    AcademicDomain.LEGAL: frozenset(
        {
            "law",
            "statute",
            "regulation",
            "court",
            "judge",
            "jurisdiction",
            "constitution",
            "amendment",
            "legislation",
            "decree",
            "ordinance",
            "legal",
            "judicial",
            "plaintiff",
            "defendant",
            "prosecution",
            "contract",
            "liability",
            "tort",
            "criminal",
            "civil",
            "rights",
            "compliance",
            "enforcement",
            "qonun",
            "huquq",
            "sud",
            "farmon",
            "qaror",
            "kodeks",
            "jinoyat",
            "fuqarolik",
            "konstitusiya",
            "tartibga solish",
            "javobgarlik",
            "закон",
            "право",
            "суд",
            "указ",
            "постановление",
            "кодекс",
            "конституция",
            "регулирование",
            "юридический",
        }
    ),
    AcademicDomain.ENGINEERING: frozenset(
        {
            "design",
            "system",
            "algorithm",
            "optimization",
            "simulation",
            "prototype",
            "manufacture",
            "material",
            "structure",
            "load",
            "stress",
            "thermal",
            "electrical",
            "circuit",
            "signal",
            "control system",
            "robotics",
            "automation",
            "sensor",
            "actuator",
            "cad",
            "finite element",
            "computational",
            "loyihalash",
            "tizim",
            "algoritm",
            "simulyatsiya",
            "проектирование",
            "система",
            "алгоритм",
            "моделирование",
        }
    ),
    AcademicDomain.ENVIRONMENTAL: frozenset(
        {
            "climate",
            "pollution",
            "ecosystem",
            "biodiversity",
            "carbon",
            "emission",
            "sustainability",
            "renewable",
            "conservation",
            "deforestation",
            "water quality",
            "air quality",
            "waste",
            "recycling",
            "ecology",
            "habitat",
            "iqlim",
            "ifloslanish",
            "ekologiya",
            "barqaror",
            "климат",
            "загрязнение",
            "экология",
            "устойчивый",
        }
    ),
    AcademicDomain.EDUCATION: frozenset(
        {
            "pedagogy",
            "curriculum",
            "student",
            "teacher",
            "learning",
            "assessment",
            "literacy",
            "classroom",
            "education policy",
            "enrollment",
            "dropout",
            "university",
            "school",
            "academic",
            "pedagogika",
            "talaba",
            "o'qituvchi",
            "ta'lim",
            "o'quv",
            "педагогика",
            "студент",
            "преподаватель",
            "образование",
        }
    ),
    AcademicDomain.AGRICULTURE: frozenset(
        {
            "crop",
            "soil",
            "irrigation",
            "fertilizer",
            "harvest",
            "livestock",
            "farming",
            "agriculture",
            "yield",
            "pesticide",
            "seed",
            "qishloq xo'jaligi",
            "ekin",
            "sug'orish",
            "tuproq",
            "hosil",
            "сельское хозяйство",
            "урожай",
            "орошение",
            "почва",
        }
    ),
    AcademicDomain.COMPUTER_SCIENCE: frozenset(
        {
            "algorithm",
            "database",
            "network",
            "machine learning",
            "neural",
            "deep learning",
            "artificial intelligence",
            "software",
            "hardware",
            "cloud",
            "cybersecurity",
            "blockchain",
            "api",
            "programming",
            "data structure",
            "compiler",
            "operating system",
            "dasturlash",
            "ma'lumotlar bazasi",
            "tarmoq",
            "sun'iy intellekt",
            "программирование",
            "база данных",
            "сеть",
            "искусственный интеллект",
        }
    ),
    AcademicDomain.SOCIAL_SCIENCES: frozenset(
        {
            "society",
            "culture",
            "gender",
            "migration",
            "urbanization",
            "demography",
            "ethnography",
            "sociology",
            "psychology",
            "anthropology",
            "political science",
            "governance",
            "democracy",
            "corruption",
            "jamiyat",
            "madaniyat",
            "migratsiya",
            "sotsiologiya",
            "общество",
            "культура",
            "миграция",
            "социология",
        }
    ),
}
