-- ============================================================================
-- 005b_identity_path_b — RLS rewrite for identity Path B ONLY
--
-- HUMAN-APPLIED, CONDITIONALLY. Apply ONLY if scripts/preflight_identity_path.py
-- exited 2 (the project cannot mint HS256 JWTs — asymmetric-signing-only — or
-- Realtime rejected a minted token). Under Path A this file must NOT be applied.
-- Requires 005_identity.sql first.
--
-- Path B uses real Supabase sessions, so auth.uid() returns auth.users.id,
-- which is NOT users.id. app_uid() bridges: it resolves the session's app
-- identity through user_auth_identities. Every owner policy below is the
-- 001/002/004/005 original with exactly one mechanical substitution:
-- auth.uid()::uuid → app_uid(). No policy gains or loses any row scope.
-- ============================================================================

-- SECURITY DEFINER: the lookup must work while RLS is active on
-- user_auth_identities itself (a plain function would recurse into the very
-- policies it powers). STABLE: one resolution per statement snapshot.
-- The unique partial index uq_user_auth_identities_auth_user (005) makes the
-- result unambiguous; no mapping → NULL → every policy denies, fail-closed.
-- search_path pins pg_temp LAST (panel finding): when pg_temp is not listed
-- explicitly, Postgres searches it FIRST — a SQL-capable authenticated session
-- could temp-shadow user_auth_identities and impersonate any app user.
--
-- TWO token shapes accepted (panel finding, 3 lenses converged): the first arm
-- resolves REAL Supabase sessions (auth.uid() = auth.users.id → identity map);
-- the second arm resolves API-minted Path A tokens (auth.uid() = users.id
-- directly). Without the second arm, applying 005b while the API still mints
-- sub=users.id would deny every user their own rows at the P1 gate. The arms
-- cannot collide: users.id values are generated app-side and auth.users.id
-- values are generated by GoTrue — a uuid matching BOTH tables at once does
-- not occur in practice, and the identity-map arm wins the lookup order.
-- NOTE: choosing Path B still requires the API-side switch to real Supabase
-- sessions (P1 code change); this fallback removes the lockout foot-gun, it
-- does not implement Path B in the API.
create or replace function app_uid() returns uuid
language sql stable security definer
set search_path = public, pg_temp
as $$
    select coalesce(
        (select user_id from user_auth_identities
         where auth_user_id = auth.uid()::uuid),
        (select id from users where id = auth.uid()::uuid)
    )
$$;

comment on function app_uid() is
    'Path B bridge: resolves the session subject to the canonical app identity '
    'users.id — via user_auth_identities for real Supabase sessions, or '
    'directly when the subject already IS a users.id (API-minted Path A '
    'token). NULL when unmapped — policies fail closed.';

-- ---------------------------------------------------------------------------
-- users (001)
-- ---------------------------------------------------------------------------
drop policy if exists users_self_select on users;
create policy users_self_select on users
    for select using (app_uid() = id);

drop policy if exists users_self_update on users;
create policy users_self_update on users
    for update using (app_uid() = id);

-- ---------------------------------------------------------------------------
-- projects (001)
-- ---------------------------------------------------------------------------
drop policy if exists projects_owner_all on projects;
create policy projects_owner_all on projects
    for all using (app_uid() = user_id);

-- ---------------------------------------------------------------------------
-- sources (001)
-- ---------------------------------------------------------------------------
drop policy if exists sources_owner_all on sources;
create policy sources_owner_all on sources
    for all using (
        exists (
            select 1 from projects p
            where p.id = sources.project_id and p.user_id = app_uid()
        )
    );

-- ---------------------------------------------------------------------------
-- source_chunks (001)
-- ---------------------------------------------------------------------------
drop policy if exists source_chunks_owner_all on source_chunks;
create policy source_chunks_owner_all on source_chunks
    for all using (
        exists (
            select 1 from projects p
            where p.id = source_chunks.project_id and p.user_id = app_uid()
        )
    );

-- ---------------------------------------------------------------------------
-- source_claims (001)
-- ---------------------------------------------------------------------------
drop policy if exists source_claims_owner_all on source_claims;
create policy source_claims_owner_all on source_claims
    for all using (
        exists (
            select 1 from projects p
            where p.id = source_claims.project_id and p.user_id = app_uid()
        )
    );

-- ---------------------------------------------------------------------------
-- research_questions (001)
-- ---------------------------------------------------------------------------
drop policy if exists research_questions_owner_all on research_questions;
create policy research_questions_owner_all on research_questions
    for all using (
        exists (
            select 1 from projects p
            where p.id = research_questions.project_id and p.user_id = app_uid()
        )
    );

-- ---------------------------------------------------------------------------
-- research_answers (001)
-- ---------------------------------------------------------------------------
drop policy if exists research_answers_owner_all on research_answers;
create policy research_answers_owner_all on research_answers
    for all using (
        exists (
            select 1 from projects p
            where p.id = research_answers.project_id and p.user_id = app_uid()
        )
    );

-- ---------------------------------------------------------------------------
-- articles (001)
-- ---------------------------------------------------------------------------
drop policy if exists articles_owner_all on articles;
create policy articles_owner_all on articles
    for all using (
        exists (
            select 1 from projects p
            where p.id = articles.project_id and p.user_id = app_uid()
        )
    );

-- ---------------------------------------------------------------------------
-- article_sections (001)
-- ---------------------------------------------------------------------------
drop policy if exists article_sections_owner_all on article_sections;
create policy article_sections_owner_all on article_sections
    for all using (
        exists (
            select 1 from articles a
            join projects p on p.id = a.project_id
            where a.id = article_sections.article_id and p.user_id = app_uid()
        )
    );

-- ---------------------------------------------------------------------------
-- decks (001)
-- ---------------------------------------------------------------------------
drop policy if exists decks_owner_all on decks;
create policy decks_owner_all on decks
    for all using (
        exists (
            select 1 from projects p
            where p.id = decks.project_id and p.user_id = app_uid()
        )
    );

-- ---------------------------------------------------------------------------
-- design_directions (001)
-- ---------------------------------------------------------------------------
drop policy if exists design_directions_owner_all on design_directions;
create policy design_directions_owner_all on design_directions
    for all using (
        exists (
            select 1 from decks d
            join projects p on p.id = d.project_id
            where d.id = design_directions.deck_id and p.user_id = app_uid()
        )
    );

-- ---------------------------------------------------------------------------
-- evidence_matrix (001)
-- ---------------------------------------------------------------------------
drop policy if exists evidence_owner_all on evidence_matrix;
create policy evidence_owner_all on evidence_matrix
    for all using (
        exists (
            select 1 from projects p
            where p.id = evidence_matrix.project_id and p.user_id = app_uid()
        )
    );

-- ---------------------------------------------------------------------------
-- orders (001)
-- ---------------------------------------------------------------------------
drop policy if exists orders_owner_select on orders;
create policy orders_owner_select on orders
    for select using (app_uid() = user_id);

-- ---------------------------------------------------------------------------
-- generation_jobs (001)
-- ---------------------------------------------------------------------------
drop policy if exists generation_jobs_owner_select on generation_jobs;
create policy generation_jobs_owner_select on generation_jobs
    for select using (
        exists (
            select 1 from projects p
            where p.id = generation_jobs.project_id and p.user_id = app_uid()
        )
    );

-- ---------------------------------------------------------------------------
-- credit_ledger (001) — append-only discipline unchanged: select + insert only
-- ---------------------------------------------------------------------------
drop policy if exists credit_ledger_owner_select on credit_ledger;
create policy credit_ledger_owner_select on credit_ledger
    for select using (app_uid() = user_id);

drop policy if exists credit_ledger_insert on credit_ledger;
create policy credit_ledger_insert on credit_ledger
    for insert with check (app_uid() = user_id);

-- ---------------------------------------------------------------------------
-- invoices (002)
-- ---------------------------------------------------------------------------
drop policy if exists invoices_owner_select on invoices;
create policy invoices_owner_select on invoices
    for select using (app_uid() = user_id);

-- ---------------------------------------------------------------------------
-- generated_files (002)
-- ---------------------------------------------------------------------------
drop policy if exists generated_files_owner_select on generated_files;
create policy generated_files_owner_select on generated_files
    for select using (
        exists (
            select 1 from projects p
            where p.id = generated_files.project_id and p.user_id = app_uid()
        )
    );

-- ---------------------------------------------------------------------------
-- brain_sessions (004)
-- ---------------------------------------------------------------------------
drop policy if exists brain_sessions_owner_all on brain_sessions;
create policy brain_sessions_owner_all on brain_sessions
    for all using (
        exists (
            select 1 from projects p
            where p.id = brain_sessions.project_id and p.user_id = app_uid()
        )
    );

-- ---------------------------------------------------------------------------
-- user_auth_identities (005) — auth_user_id disjunct kept: under Path B the
-- session IS an auth.users id, and app_uid() covers rows repointed by merge.
-- ---------------------------------------------------------------------------
drop policy if exists user_auth_identities_owner_select on user_auth_identities;
create policy user_auth_identities_owner_select on user_auth_identities
    for select using (
        app_uid() = user_id or auth.uid()::uuid = auth_user_id
    );

-- ============================================================================
-- DOWN (manual rollback, per .claude/rules/database.md): re-apply the policy
-- blocks from 001/002/004/005 verbatim (each is a drop-if-exists + create
-- keyed to auth.uid()::uuid — they are the exact pre-005b state), then:
--
--   drop function if exists app_uid();
-- ============================================================================
